version: '3.8'

services:
  web:
    build: .
    container_name: online-courses-app
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - online-courses-network

networks:
  online-courses-network:
    driver: bridge